version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: car_rental_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: car_rental_db
      MYSQL_USER: caruser
      MYSQL_PASSWORD: carpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  car-rental-service:
    build: .
    container_name: car_rental_service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_rental_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: caruser
      SPRING_DATASOURCE_PASSWORD: carpass
    ports:
      - "8080:8080"

volumes:
  mysql-data:
