spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: caruser
    password: carpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.xyz: DEBUG

license:
  service:
    url: http://localhost:8080

rate:
  service:
    url: http://localhost:8080

api:
  license-url: /license/details
  rate-url: /rental/rate